title: Sanches
# email: your-email@example.com
description: >-
  "A simplicidade é o último grau de sofisticação" Leonardo da Vinci

url: https://sancheslz.github.io
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  sancheslz
linkedin_username: sancheslucas
twitter_username: sanches_lz

google_analytics: UA-177397165-1
google_tag_manager: GTM-MRF2CB2

disqus:
  shortname: sancheslz


permalink: /:slug

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
